rethinkdb:
  image: rethinkdb:2.3.0
  ports:
   - "8080:8080"
   - "28015"
   - "29015"
comment-wall:
  build: ./app
  links:
    - rethinkdb
  ports:
    - "3000:3000"
  environment:
    STANDALONE: "true"